// WARNING: DO NOT EDIT. This file is automatically generated by AWS Amplify. It will be overwritten.

const awsmobile = {
  'aws_project_region': 'eu-central-1',
  'aws_cognito_identity_pool_id': 'eu-central-1:5911a9ff-afa8-4852-a362-a1d269b7deeb',
  'aws_cognito_region': 'eu-central-1',
  'aws_user_pools_id': 'eu-central-1_nwdCBsQz1',
  'aws_user_pools_web_client_id': '20c1p7o7uhl00atv2buvt69olg',
  'oauth': {}
}

export default awsmobile
