version: '3.6'
services:
  db:
    image: postgres:10-alpine
    container_name: fundraiser-db
    environment:
      POSTGRES_PASSWORD: postgres
      POSTGRES_USER: postgres
      POSTGRES_DB: fundraiser
    ports:
      - "5433:5432"
    networks:
      - backdb
    volumes:
      - "./initdb:/docker-entrypoint-initdb.d"
  
  server:
    image: fundraiser-server
    container_name: fundraiser-server
    ports:
      - 8085:8085
    depends_on:
      - db
    networks:
      - frontback 
      - backdb

  client:
    image: fundraiser-client
    container_name: fundraiser-client
    ports:
      - 8080:8080
    depends_on:
      - server
    networks: 
      - frontback
  
networks: 
  backdb:
    driver: bridge
  frontback:
    driver: bridge
